/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;
import java.awt.Dimension;
import java.awt.Toolkit;
import backend.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author user
 */
public class FormKaryawan extends javax.swing.JFrame {

    /**
     * Creates new form FromKaryawan
     */
    public FormKaryawan() {
        initComponents();
        tampilkanData();
        kosongkanForm();
        
        // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdKaryawan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtJenisKelamin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelepon = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        txtTambahBaru = new javax.swing.JButton();
        txtHapus = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKaryawan = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Magneto", 1, 48)); // NOI18N
        jLabel2.setText("KARYAWAN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 460, 90));

        jLabel3.setText("ID Karyawan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        txtIdKaryawan.setEnabled(false);
        jPanel1.add(txtIdKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 60, -1));

        jLabel4.setText("Nama");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 210, 30));

        jLabel5.setText("Jenis Kelamin");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));
        jPanel1.add(txtJenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 40, -1));

        jLabel6.setText("Alamat");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));
        jPanel1.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 190, 70));

        jLabel7.setText("Telepon");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));
        jPanel1.add(txtTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 190, -1));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, -1, -1));

        txtTambahBaru.setText("Tambah Baru");
        txtTambahBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTambahBaruActionPerformed(evt);
            }
        });
        jPanel1.add(txtTambahBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, -1, -1));

        txtHapus.setText("Hapus");
        txtHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHapusActionPerformed(evt);
            }
        });
        jPanel1.add(txtHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, -1, -1));

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });
        jPanel1.add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, -1, -1));
        jPanel1.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 150, 30));

        tblKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKaryawanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKaryawan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 820, 160));

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\tubes\\src\\frontend\\dashbord.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        Karyawan kry = new Karyawan();
        kry.setIdkaryawan(Integer.parseInt(txtIdKaryawan.getText()));
        kry.setNama(txtNama.getText());
        kry.setJeniskelamin(txtJenisKelamin.getText());
        kry.setAlamat(txtAlamat.getText());
        kry.setTelepon(txtTelepon.getText());
        kry.save();
        txtIdKaryawan.setText(Integer.toString(kry.getIdkaryawan()));
        tampilkanData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtTambahBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTambahBaruActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_txtTambahBaruActionPerformed

    private void txtHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblKaryawan.getModel();
        int row = tblKaryawan.getSelectedRow();
        
        Karyawan kry = new Karyawan().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        kry.delete();
        kosongkanForm();
        tampilkanData();
    }//GEN-LAST:event_txtHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
         cari(txtCari.getText());
    }//GEN-LAST:event_btnCariActionPerformed

    private void tblKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKaryawanMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)tblKaryawan.getModel();
        int row = tblKaryawan.getSelectedRow();
        
        txtIdKaryawan.setText(model.getValueAt(row, 0).toString());
        txtNama.setText(model.getValueAt(row, 1).toString());
        txtJenisKelamin.setText(model.getValueAt(row, 2).toString());
        txtAlamat.setText(model.getValueAt(row, 3).toString());
        txtTelepon.setText(model.getValueAt(row, 4).toString());
        
    }//GEN-LAST:event_tblKaryawanMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FromHalamanAwal ha = new FromHalamanAwal();
        ha.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void kosongkanForm(){
       txtIdKaryawan.setText("0");
       txtNama.setText("");
       txtJenisKelamin.setText("");
       txtAlamat.setText("");
       txtTelepon.setText("");
   }
   public void tampilkanData(){
       String[] kolom = {"ID", "Nama", "Jenis Kelamin", "Alamat", "Telepon"};
       ArrayList<Karyawan> list = new Karyawan().getAll();
       Object rowData[] = new Object[5];
       
       tblKaryawan.setModel(new DefaultTableModel(new Object[][] {}, kolom));
       
       for(Karyawan kry : list){
           rowData[0] = kry.getIdkaryawan();
           rowData[1] = kry.getNama();
           rowData[2] = kry.getJeniskelamin();
           rowData[3] = kry.getAlamat();
           rowData[4] = kry.getTelepon();
           
           ((DefaultTableModel)tblKaryawan.getModel()).addRow(rowData);
            
        }
    }
   
   public void cari(String keyword){
       String[] kolom = {"ID", "Nama", "Jenis Kelamin", "Alamat", "Telepon"};
       ArrayList<Karyawan> list = new Karyawan().search(keyword);
       Object rowData[] = new Object[5];
       
       tblKaryawan.setModel(new DefaultTableModel(new Object[][] {}, kolom));
       
       for(Karyawan kry : list){
           rowData[0] = kry.getIdkaryawan();
           rowData[1] = kry.getNama();
           rowData[2] = kry.getJeniskelamin();
           rowData[3] = kry.getAlamat();
           rowData[4] = kry.getTelepon();
           
           ((DefaultTableModel)tblKaryawan.getModel()).addRow(rowData);
            
        }
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKaryawan;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JButton txtHapus;
    private javax.swing.JTextField txtIdKaryawan;
    private javax.swing.JTextField txtJenisKelamin;
    private javax.swing.JTextField txtNama;
    private javax.swing.JButton txtTambahBaru;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables
}
