/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frontend;

import java.awt.Dimension;
import java.awt.Toolkit;
import backend.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class FormPeminjaman extends javax.swing.JFrame {

    /**
     * Creates new form FormPeminjaman
     */
    
    public void kosongkanForm() {
        txtpinjam.setText("0");
        txtkaryawan.setText("0");
        txtpengguna.setText("0");
        txtsepeda.setText("0");
        txttanggalpinjam.setText("");
        txttanggalkembali.setText("");
        txtjumlahsepeda.setText("");
        txthari.setText("");
        txtharga.setText("");
    }
    
    public void tampilkanData() {
        String[] kolom = {"ID Peminjaman", "ID Karyawan", "ID Pengguna", 
            "ID Sepeda", "Tanggal Pinjam", "Tanggal Kembali", "Jumlah Sepeda", "Hari", "Harga", "Total Harga"};
        ArrayList<Peminjaman> list = new Peminjaman().getAll();
        Object rowData[] = new Object[10];

        tabelpinjam.setModel(new DefaultTableModel(new Object[][]{}, kolom));

        for (int i = 0; i < list.size(); i++) {
            rowData[0] = list.get(i).getIdpeminjaman();
            rowData[1] = list.get(i).getKaryawan().getIdkaryawan();
            rowData[2] = list.get(i).getPenggunaku().getIdku();
            rowData[3] = list.get(i).getSepeda().getIdsepeda();
            rowData[4] = list.get(i).getWaktupeminjaman();
            rowData[5] = list.get(i).getWaktupengembalian();
            rowData[6] = list.get(i).getJumlahsepeda();
            rowData[7] = list.get(i).getHari();
            rowData[8] = list.get(i).getHarga();
            rowData[9] = list.get(i).getTotal();
            
            ((DefaultTableModel)tabelpinjam.getModel()).addRow(rowData);
        }
    }
    
    public void cari(String keyword) {
        String[] kolom = {"ID Peminjaman", "ID Karyawan", "ID Pengguna", "ID Sepeda", 
            "Tanggal Pinjam", "Tanggal Kembali", "Jumlah Sepeda", "Hari", "Harga", "Total Harga"};
        ArrayList<Peminjaman> list = new Peminjaman().search(keyword);
        Object rowData[] = new Object[10];

        tabelpinjam.setModel(new DefaultTableModel(new Object[][]{}, kolom));

        for (Peminjaman pinjam : list) {
            rowData[0] = pinjam.getIdpeminjaman();
            rowData[1] = pinjam.getKaryawan().getIdkaryawan();
            rowData[2] = pinjam.getPenggunaku().getIdku();
            rowData[3] = pinjam.getSepeda().getIdsepeda();
            rowData[4] = pinjam.getWaktupeminjaman();
            rowData[5] = pinjam.getWaktupengembalian();
            rowData[6] = pinjam.getJumlahsepeda();
            rowData[7] = pinjam.getHari();
            rowData[8] = pinjam.getHarga();
            rowData[9] = pinjam.getTotal();

            ((DefaultTableModel)tabelpinjam.getModel()).addRow(rowData);
        }
    }
    
    public Karyawan cariKaryawan(String keyword) {
        return new Karyawan().getById(Integer.parseInt(keyword));
    }

    public PenggunaKu cariPengguna(String keyword) {
        return new PenggunaKu().getById(Integer.parseInt(keyword));
    }
    
    public Sepeda cariSepeda(String keyword) {
        return new Sepeda().getById(Integer.parseInt(keyword));
    }
    
    public FormPeminjaman() {
        initComponents();
        tampilkanData();
        kosongkanForm();
        
        // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtpinjam = new javax.swing.JTextField();
        txtkaryawan = new javax.swing.JTextField();
        btnkaryawan = new javax.swing.JButton();
        namakaryawan = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtpengguna = new javax.swing.JTextField();
        btnpengguna = new javax.swing.JButton();
        namapengguna = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtsepeda = new javax.swing.JTextField();
        txttanggalkembali = new javax.swing.JTextField();
        tglpinjam = new javax.swing.JLabel();
        tglkembali = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txttanggalpinjam = new javax.swing.JTextField();
        btnsepeda = new javax.swing.JButton();
        namasepeda = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelpinjam = new javax.swing.JTable();
        btnsimpan = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        tglkembali1 = new javax.swing.JLabel();
        txtjumlahsepeda = new javax.swing.JTextField();
        tglkembali3 = new javax.swing.JLabel();
        txthari = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        tglkembali6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tglkembali2 = new javax.swing.JLabel();
        tglkembali4 = new javax.swing.JLabel();
        txttanggalkembali3 = new javax.swing.JTextField();
        btnkaryawan1 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Sylfaen", 1, 30)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("FORM SEWA SEPEDA");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        jButton1.setText("Kembali Ke Menu Utama");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(933, 40, 220, 40));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Peminjaman");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID Karyawan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        txtpinjam.setEnabled(false);
        txtpinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpinjamActionPerformed(evt);
            }
        });
        jPanel1.add(txtpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 128, -1));

        txtkaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkaryawanActionPerformed(evt);
            }
        });
        jPanel1.add(txtkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 128, -1));

        btnkaryawan.setText("Cari");
        btnkaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkaryawanActionPerformed(evt);
            }
        });
        jPanel1.add(btnkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 88, -1));

        namakaryawan.setForeground(new java.awt.Color(255, 255, 255));
        namakaryawan.setText("Nama Karyawan");
        jPanel1.add(namakaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Pengguna");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        txtpengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpenggunaActionPerformed(evt);
            }
        });
        jPanel1.add(txtpengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 128, -1));

        btnpengguna.setText("Cari");
        btnpengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpenggunaActionPerformed(evt);
            }
        });
        jPanel1.add(btnpengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 88, -1));

        namapengguna.setForeground(new java.awt.Color(255, 255, 255));
        namapengguna.setText("Nama Pengguna");
        jPanel1.add(namapengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID Sepeda");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        txtsepeda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsepedaActionPerformed(evt);
            }
        });
        jPanel1.add(txtsepeda, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 128, -1));
        jPanel1.add(txttanggalkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 131, -1));

        tglpinjam.setForeground(new java.awt.Color(255, 255, 255));
        tglpinjam.setText("Tanggal Pinjam");
        jPanel1.add(tglpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        tglkembali.setForeground(new java.awt.Color(255, 255, 255));
        tglkembali.setText("Tanggal Kembali");
        jPanel1.add(tglkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Format: YYYY/MM/DD");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 180, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Format: YYYY/MM/DD");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, -1, -1));

        txttanggalpinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttanggalpinjamActionPerformed(evt);
            }
        });
        jPanel1.add(txttanggalpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 128, -1));

        btnsepeda.setText("Cari");
        btnsepeda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsepedaActionPerformed(evt);
            }
        });
        jPanel1.add(btnsepeda, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 88, -1));

        namasepeda.setForeground(new java.awt.Color(255, 255, 255));
        namasepeda.setText("Nama Sepeda");
        jPanel1.add(namasepeda, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, -1, -1));

        tabelpinjam.setAutoCreateRowSorter(true);
        tabelpinjam.setBackground(new java.awt.Color(0, 204, 204));
        tabelpinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Peminjaman", "ID Karyawan", "ID Pengguna", "ID Sepeda", "Tanggal Pinjam", "Tanggal Kembali", "Jumlah Sepeda", "Hari", "Harga", "Total"
            }
        ));
        jScrollPane2.setViewportView(tabelpinjam);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 1160, 120));

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 88, -1));

        btntambah.setText("Tambah Data Peminjaman");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });
        jPanel1.add(btntambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, -1, -1));

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 590, -1, -1));

        tglkembali1.setForeground(new java.awt.Color(255, 255, 255));
        tglkembali1.setText("Jumlah Sepeda");
        jPanel1.add(tglkembali1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, 20));
        jPanel1.add(txtjumlahsepeda, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 131, -1));

        tglkembali3.setForeground(new java.awt.Color(255, 255, 255));
        tglkembali3.setText("Hari");
        jPanel1.add(tglkembali3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));
        jPanel1.add(txthari, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 131, -1));
        jPanel1.add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 131, -1));

        tglkembali6.setForeground(new java.awt.Color(255, 255, 255));
        tglkembali6.setText("Harga");
        jPanel1.add(tglkembali6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontend/kategori.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 820));

        tglkembali2.setForeground(new java.awt.Color(255, 255, 255));
        tglkembali2.setText("Jumlah Sepeda");
        jPanel1.add(tglkembali2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        tglkembali4.setForeground(new java.awt.Color(255, 255, 255));
        tglkembali4.setText("Hari");
        jPanel1.add(tglkembali4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));
        jPanel1.add(txttanggalkembali3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 131, -1));

        btnkaryawan1.setText("Cari");
        btnkaryawan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkaryawan1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnkaryawan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 88, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtkaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkaryawanActionPerformed

    private void txtpenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpenggunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpenggunaActionPerformed

    private void txtsepedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsepedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsepedaActionPerformed

    private void txttanggalpinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttanggalpinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttanggalpinjamActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        Peminjaman pinjam = new Peminjaman();
        pinjam.setIdpeminjaman(Integer.parseInt(txtpinjam.getText()));
        pinjam.setKaryawan(new Karyawan().getById(Integer.parseInt(txtkaryawan.getText())));
        pinjam.setPenggunaku(new PenggunaKu().getById(Integer.parseInt(txtpengguna.getText())));
        pinjam.setSepeda(new Sepeda().getById(Integer.parseInt(txtsepeda.getText())));
        pinjam.setWaktupeminjaman(txttanggalpinjam.getText());
        pinjam.setWaktupengembalian(txttanggalkembali.getText());
        pinjam.setJumlahsepeda(Integer.parseInt(txtjumlahsepeda.getText()));
        pinjam.setHari(Integer.parseInt(txthari.getText()));
        pinjam.setHarga(Integer.parseInt(txtharga.getText()));
        
        int a = Integer.parseInt(txtjumlahsepeda.getText());
        int b = Integer.parseInt(txthari.getText());
        int c = Integer.parseInt(txtharga.getText());
        int hasil = a*b*c;
        pinjam.setTotal(hasil);
        pinjam.save();
        txtpinjam.setText(Integer.toString(pinjam.getIdpeminjaman()));
        tampilkanData();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnpenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpenggunaActionPerformed
        // TODO add your handling code here:
        namapengguna.setText(cariPengguna(txtpengguna.getText()).getNama());
    }//GEN-LAST:event_btnpenggunaActionPerformed

    private void btnkaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkaryawanActionPerformed
        // TODO add your handling code here:
        namakaryawan.setText(cariKaryawan(txtkaryawan.getText()).getNama());
    }//GEN-LAST:event_btnkaryawanActionPerformed

    private void btnsepedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsepedaActionPerformed
        // TODO add your handling code here:
        namasepeda.setText(cariSepeda(txtsepeda.getText()).getNama());
    }//GEN-LAST:event_btnsepedaActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tabelpinjam.getModel();
        int row = tabelpinjam.getSelectedRow();
        
        Peminjaman pinjam = new Peminjaman().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        pinjam.delete();
        kosongkanForm();
        tampilkanData();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void txtpinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpinjamActionPerformed

    private void btnkaryawan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkaryawan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnkaryawan1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FromHalamanAwal pinjam = new FromHalamanAwal();
        pinjam.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPeminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkaryawan;
    private javax.swing.JButton btnkaryawan1;
    private javax.swing.JButton btnpengguna;
    private javax.swing.JButton btnsepeda;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel namakaryawan;
    private javax.swing.JLabel namapengguna;
    private javax.swing.JLabel namasepeda;
    private javax.swing.JTable tabelpinjam;
    private javax.swing.JLabel tglkembali;
    private javax.swing.JLabel tglkembali1;
    private javax.swing.JLabel tglkembali2;
    private javax.swing.JLabel tglkembali3;
    private javax.swing.JLabel tglkembali4;
    private javax.swing.JLabel tglkembali6;
    private javax.swing.JLabel tglpinjam;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txthari;
    private javax.swing.JTextField txtjumlahsepeda;
    private javax.swing.JTextField txtkaryawan;
    private javax.swing.JTextField txtpengguna;
    private javax.swing.JTextField txtpinjam;
    private javax.swing.JTextField txtsepeda;
    private javax.swing.JTextField txttanggalkembali;
    private javax.swing.JTextField txttanggalkembali3;
    private javax.swing.JTextField txttanggalpinjam;
    // End of variables declaration//GEN-END:variables
}
